### ISSUE TITLE
Box<[u8]> vs Vec<u8> as bytes representation

### ISSUE THREAD

**Issue by dvc94ch** [ipld/libipld#36]
My take on it:

1. having different implementations of a trait for `Vec<T>` and `Box<[u8]>` is useful
2. an immutable opaque blob of bytes is a `Box<[u8]>`. a `Vec<u8>` represents a mutable buffer or a list of `u8` that may or may not be bytes.

cc @dignifiedquire @vmx @aphelionz @koivunej @rklaehn

**Comment by aphelionz** [comment]
Perhaps a cop-out answer but it is it possible to support both, at least at the `rust-cid` level, that way implementers of higher-level crates can choose their preference.

I personally prefer `Box<[u8]>` as it signals to the reader the fixed size, but due to `to_vec` and `to_boxed_slice` it also feels like "six in one hand / half dozen in the other."

**Comment by koivunej** [comment]
I haven't seen much of `Box<[u8]>` outside of some std internals, like [`std::io::BufReader`](https://doc.rust-lang.org/src/std/io/buffered.rs.html#56). I'd say the `Vec<u8>` as a growable buffer is quite common, like in [`std::io::Read::read_to_end`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_end).

> an immutable opaque blob of bytes is a `Box<[u8]>`

I'd rather read it as hint of fixed length being somehow *important*, nothing about immutability. I would definitely read a comment explaining why the fixed length was important :) For example in `BufReader` the fixed length is important.

> a `Vec<u8>` represents a mutable buffer or a list of `u8`

Yeah the latter could be possible, while I've rarely seen it used in such a way. Probably because std is full of usages of anything-u8 as a some kind of byte buffer or another. I guess I'd prefer to newtype a `Vec<u8>` if it had more of a "list of" small numbers meaning instead of bytes, since the u8 would likely be used as an optimization of some sort.

**Comment by dvc94ch** [comment]
New typing Vec<u8> doesn't help with implementing traits. I still question the utility of vec methods on bytes. The only thing you want to do on bytes is deref them. The only case I can think of would be the special case where the cid happens to be the first byte sequence in a longer byte sequence. But that's why a copy_to_slice was suggested

**Comment by vmx** [comment]
I searched around a bit but didn't find anything significant. Most notable is perhaps an old discussion at the [OpenEthereum project](https://github.com/openethereum/openethereum/issues/5936) where they didn't bother changing from Vec to a Boxed Slice because of too much existing code (we don't have that problem).

So to me it seems uncommon to use Boxed Slices instead of Vectors in the Rust ecosystem, but I also couldn't really find any hard numbers or guidelines on this.

I hope others have with more experience chime into this discussion.
